# syntax=docker/dockerfile:1

# require >= 1.25.12 for CVE-2026-25679, CVE-2026-39822, and other Go stdlib CVEs
FROM golang:1.25.12 AS build
COPY ./services/core/jobs/jobs-launcher /app/services/jobs-launcher
WORKDIR /app/services/jobs-launcher
RUN go mod download
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags="-s -w -extldflags '-static'" -trimpath -o jobs-launcher ./main.go
# Verify the binary works
RUN ./jobs-launcher help

FROM scratch AS artifacts
WORKDIR /artifacts
COPY --from=build /app/services/jobs-launcher/jobs-launcher .
# Outputs the static binary to /artifacts/jobs-launcher
