# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Public value types for evaluator SDK runtime."""

# ruff: noqa: I001 - the vendored SDK mirror uses different import-order settings.

from nemo_platform.beta.evaluator.values.agents import (
    Agent,
    AgentBase,
    GenericAgent,
    NatAgentConfig,
    NemoAgentToolkitAgent,
)
from nemo_platform.beta.evaluator.values.atif import (
    FinalMetrics,
    Metrics,
    Observation,
    ObservationResult,
    Step,
    ToolCall,
    Trajectory,
)
from nemo_platform.beta.evaluator.values.common import SecretRef, SupportedJobTypes
from nemo_platform.beta.evaluator.values.dataset_schemas import (
    FieldMapping,
    InputSchema,
)
from nemo_platform.beta.evaluator.values.datasets import DatasetInput, DatasetRows
from nemo_platform.beta.evaluator.values.evidence import (
    CandidateEvidence,
    CommandResult,
    EvidenceDescriptor,
    FilesystemDiff,
    FilesystemEntry,
    LocalFilesystemEvidence,
    LogHandle,
    TraceHandle,
    WellKnownEvidenceKey,
    parse_atif,
)
from nemo_platform.beta.evaluator.values.metrics import (
    BLEU,
    F1,
    ROUGE,
    AgentGoalAccuracy,
    AnswerAccuracy,
    ContextEntityRecall,
    ContextPrecision,
    ContextRecall,
    ContextRelevance,
    ExactMatch,
    Faithfulness,
    LLMJudge,
    MetricBase,
    NemoAgentToolkitRemote,
    NoiseSensitivity,
    NumberCheck,
    Remote,
    ResponseGroundedness,
    ResponseRelevancy,
    StringCheck,
    ToolCallAccuracy,
    ToolCalling,
    TopicAdherence,
)
from nemo_platform.beta.evaluator.values.models import Model, ModelRef, ReasoningParams
from nemo_platform.beta.evaluator.values.params import (
    InferenceParams,
    RunConfig,
    RunConfigOnline,
    RunConfigOnlineModel,
)
from nemo_platform.beta.evaluator.values.protocol import (
    BooleanValue,
    CandidateOutput,
    ContinuousScore,
    DatasetRow,
    DiscreteScore,
    Label,
    MetricDescriptor,
    MetricDiagnostic,
    MetricInput,
    MetricOutput,
    MetricOutputSpec,
    MetricResult,
    MetricTypeName,
)
from nemo_platform.beta.evaluator.values.results import (
    AggregatedMetricResult,
    AggregateFieldName,
    AggregateRangeScore,
    AggregateRubricScore,
    AggregateScore,
    AggregateScoreBase,
    DefaultAggregateFieldName,
    EvaluationResult,
    Histogram,
    HistogramBin,
    MetricScore,
    Percentiles,
    RowScore,
    RubricScoreStat,
    RubricScoreValue,
    SampleResult,
    ScoreStats,
)
from nemo_platform.beta.evaluator.values.scores import (
    JSONScoreParser,
    RangeScore,
    RegexScoreParser,
    RemoteScore,
    Rubric,
    RubricScore,
    Score,
    score_discriminator,
)

__all__ = [
    "Agent",
    "AgentBase",
    "GenericAgent",
    "NatAgentConfig",
    "NemoAgentToolkitAgent",
    "AggregateFieldName",
    "AggregatedMetricResult",
    "AggregateRangeScore",
    "AggregateRubricScore",
    "AggregateScore",
    "AggregateScoreBase",
    "BooleanValue",
    "CandidateEvidence",
    "CandidateOutput",
    "CommandResult",
    "ContinuousScore",
    "FilesystemDiff",
    "FilesystemEntry",
    "FinalMetrics",
    "LogHandle",
    "Metrics",
    "Observation",
    "ObservationResult",
    "Step",
    "ToolCall",
    "Trajectory",
    "TraceHandle",
    "WellKnownEvidenceKey",
    "parse_atif",
    "DatasetRow",
    "DatasetRows",
    "DefaultAggregateFieldName",
    "DiscreteScore",
    "RunConfig",
    "RunConfigOnline",
    "RunConfigOnlineModel",
    "FieldMapping",
    "Histogram",
    "HistogramBin",
    "InferenceParams",
    "JSONScoreParser",
    "Label",
    "LocalFilesystemEvidence",
    "MetricDescriptor",
    "MetricDiagnostic",
    "MetricInput",
    "MetricOutput",
    "MetricOutputSpec",
    "MetricResult",
    "MetricTypeName",
    "MetricScore",
    "Model",
    "ModelRef",
    "DatasetInput",
    "EvaluationResult",
    "EvidenceDescriptor",
    "Percentiles",
    "RangeScore",
    "ReasoningParams",
    "InputSchema",
    "RegexScoreParser",
    "RemoteScore",
    "RowScore",
    "Rubric",
    "RubricScore",
    "RubricScoreStat",
    "RubricScoreValue",
    "SampleResult",
    "Score",
    "ScoreStats",
    "SecretRef",
    "SupportedJobTypes",
    "score_discriminator",
    # Metrics
    "AgentGoalAccuracy",
    "AnswerAccuracy",
    "BLEU",
    "ContextEntityRecall",
    "ContextPrecision",
    "ContextRecall",
    "ContextRelevance",
    "ExactMatch",
    "F1",
    "Faithfulness",
    "LLMJudge",
    "MetricBase",
    "NemoAgentToolkitRemote",
    "NoiseSensitivity",
    "NumberCheck",
    "Remote",
    "ResponseGroundedness",
    "ResponseRelevancy",
    "ROUGE",
    "StringCheck",
    "ToolCallAccuracy",
    "ToolCalling",
    "TopicAdherence",
]
