platform:
  runtime: "none"
  base_url: "http://0.0.0.0:8080"
  loopback_address: "nemo-gateway"

service: {}

auth:
  enabled: true
  allow_unsigned_jwt: false
  policy_decision_point_provider: embedded
  policy_decision_point_base_url: "http://127.0.0.1:8080"
  policy_data_refresh_interval: 2
  bundle_cache_seconds: 15
  admin_email: "admin@example.com"
  oidc:
    enabled: true
    issuer: "http://authentik-server:9000/application/o/nemo-cli/"
    additional_issuers:
      - "http://authentik-server:9000/application/o/nemo/"
      - "http://127.0.0.1:18080/application/o/nemo-cli/"
      - "http://127.0.0.1:18080/application/o/nemo/"
    client_id: "nemo-platform-cli"
    token_endpoint: "http://127.0.0.1:18080/application/o/token/"
    device_authorization_endpoint: "http://127.0.0.1:18080/application/o/device/"
    subject_claim: "sub"
    email_claim: "email"
    groups_claim: "groups"
    default_scopes: "openid email offline_access groups"

entities: {}

jobs:
  enable_subprocess_executor: false
  executors:
    - provider: cpu
      profile: workload
      backend: docker
      config:
        cleanup_completed_jobs_immediately: false
        launcher_tool_path: /tools/jobs-launcher
  executor_defaults:
    docker:
      cleanup_completed_jobs_immediately: false
      launcher_tool_path: /tools/jobs-launcher
      ttl_seconds_before_active: 60
      ttl_seconds_active: 3600
      ttl_seconds_after_finished: 300

evaluator:
  recreate_existing_system_entities: true

safe_synthesizer: {}

models:
  controller:
    interval_seconds: 5
    model_deployment_garbage_collection_ttl_seconds: 30

inference_gateway: {}

secrets:
  allow_key_creation: true

files:
  default_storage_config:
    type: local
    path: /data/files

studio:
  static_files_path: /static/studio
  sandbox_enabled: true
