# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import asyncio
import logging
from datetime import datetime, timezone
from typing import Literal, cast, get_args

import nmp.evaluator.app.values as app
import nmp.evaluator.entities as entities
from nemo_evaluator_sdk.execution.metric_execution import (
    ComputeMetricPipeline,
    run_generated_sample_scoring_pipeline,
)
from nemo_evaluator_sdk.execution.scoring import finalize_evaluation_result
from nemo_evaluator_sdk.execution.values import EvaluationError
from nemo_evaluator_sdk.metrics.utils import metric_type_name
from nemo_evaluator_sdk.resilience.errors import get_evaluation_error
from nemo_evaluator_sdk.resolver_protocols import SecretResolver
from nemo_evaluator_sdk.values import (
    AggregateFieldName,
    DatasetRows,
    DefaultAggregateFieldName,
    SecretRef,
    SupportedJobTypes,
)
from nemo_evaluator_sdk.values.metrics import _RAGASEmbeddingsConfig, _RAGASJudgeConfig
from nemo_platform import AsyncNeMoPlatform, NotFoundError
from nemo_platform_plugin.entities import EntityClient
from nemo_platform_plugin.jobs.api_factory import PlatformJobSpec
from nmp.common.api.common import DeleteResponse, PaginationData
from nmp.common.api.common import SecretRef as ApiSecretRef
from nmp.common.api.parsed_filter import ParsedFilter
from nmp.common.entities import SYSTEM_WORKSPACE, EntityBase, EntityNotFoundError, ListResponse
from nmp.common.observability.otel import MARK_INTERNAL_REQUEST_HEADERS, scoped_otel_headers
from nmp.common.sdk_factory import get_async_platform_sdk
from nmp.evaluator.api.v2.common.checks import CompositeCheck
from nmp.evaluator.api.v2.common.model_resolution import (
    ResolvableModels,
    resolve_model,
    resolve_params_model_refs,
    rewrite_models_for_job_container,
)
from nmp.evaluator.api.v2.metrics.checks import (
    job_fileset_exists_check,
    job_model_check,
    metric_dataset_schema_check,
)
from nmp.evaluator.api.v2.metrics.mapper import MetricMapper
from nmp.evaluator.api.v2.metrics.schemas.evaluation import (
    MetricEvaluationResponse,
    MetricEvaluationRowScore,
)
from nmp.evaluator.api.v2.metrics.schemas.jobs import MetricJob, MetricOnlineJob, MetricRetrieverJob
from nmp.evaluator.api.v2.metrics.schemas.metrics import Metric
from nmp.evaluator.api.v2.metrics.schemas.metrics_resp import (
    MetricJobResult,
    MetricJobResultsListResponse,
    MetricResponse,
    MetricResponseAdapter,
    MetricsListResponse,
)
from nmp.evaluator.app.evalfactory.system import get_all_system_metrics
from nmp.evaluator.app.jobs.metrics import compile_metric_job
from nmp.evaluator.app.metrics.metric import new_metric
from pydantic import BaseModel
from tenacity import retry, stop_after_attempt, wait_exponential

_logger = logging.getLogger(__name__)


class _PlatformSecretResolver:
    """Resolve evaluator SDK secret refs through the request-scoped platform SDK."""

    def __init__(self, *, workspace: str, sdk: AsyncNeMoPlatform) -> None:
        self._workspace = workspace
        self._sdk = sdk

    async def resolve_secret(self, secret_ref: SecretRef) -> str | None:
        try:
            secret = await self._sdk.secrets.access(secret_ref.root, workspace=self._workspace)
            return secret.value
        except NotFoundError as e:
            raise MetricEvaluationError(
                "SECRET_NOT_FOUND",
                f"Secret '{self._workspace}/{secret_ref.root}' required by metric not found.",
            ) from e


def _append_model_secret(secrets: list[SecretRef | ApiSecretRef], model: object) -> None:
    secret = getattr(model, "api_key_secret", None)
    if isinstance(secret, SecretRef | ApiSecretRef):
        secrets.append(secret)


# Fields generated by the entity store that should be excluded from metric comparisons
_ENTITY_METADATA_FIELDS = {"id", "entity_id", "created_at", "updated_at"}


def _metrics_equal(metric1: BaseModel, metric2: BaseModel) -> bool:
    """Compare two metrics, ignoring database-generated metadata fields."""
    return metric1.model_dump(exclude=_ENTITY_METADATA_FIELDS) == metric2.model_dump(exclude=_ENTITY_METADATA_FIELDS)


def _default_aggregate_fields() -> frozenset[AggregateFieldName]:
    """Return the default aggregate fields with the literal type retained for ty."""
    return cast(frozenset[AggregateFieldName], frozenset(get_args(DefaultAggregateFieldName)))


MetricsServiceError = Literal[
    "METRIC_JOB_RESULT_NOT_FOUND",
    "METRIC_NOT_FOUND",
    "SECRET_NOT_FOUND",
    "INVALID_METRIC",
    "DATASET_NOT_FOUND",
    "EVALUATION_FAILED",
]

DEFAULT_PARALLELISM = 8


class _MetricsServiceError(Exception):
    error_code: MetricsServiceError
    detail: str

    def __init__(self, error_code: MetricsServiceError, detail: str):
        super().__init__(f"{error_code}: {detail}")
        self.error_code = error_code
        self.detail = detail


class MetricCreationError(_MetricsServiceError): ...


class MetricRetrievalError(_MetricsServiceError): ...


class MetricDeletionError(_MetricsServiceError): ...


class MetricEvaluationError(_MetricsServiceError): ...


class MetricResolutionError(_MetricsServiceError): ...


class MetricsManager:
    def __init__(self, entity_client: EntityClient, *, as_service: str | None = None):
        self._entity_client = entity_client
        self._as_service = as_service
        self._mapper = MetricMapper()

    async def get_all(
        self,
        *,
        workspace: str,
        page: int = 1,
        page_size: int = 100,
        sort: Literal["-created_at", "created_at", "-updated_at", "updated_at", "-name", "name"] = "-created_at",
        parsed_filter: ParsedFilter | None = None,
    ) -> MetricsListResponse:
        filter_op = parsed_filter.operation if parsed_filter else None
        resp = await self._entity_client.list(
            entities.Metric,
            workspace=workspace,
            sort=sort,
            page=page,
            page_size=page_size,
            filter_operation=filter_op,
        )
        return MetricsListResponse(
            data=[self._mapper.entity_to_schema_via_adapter(metric, MetricResponseAdapter) for metric in resp.data],
            pagination=PaginationData(**resp.pagination.model_dump()),
            sort=sort,
            filter=parsed_filter.to_response() if parsed_filter else None,
        )

    async def get_by_name(self, workspace: str, name: str) -> MetricResponse:
        try:
            if workspace == SYSTEM_WORKSPACE:
                metric = await self._entity_client.get(entities.SystemMetric, workspace=workspace, name=name)
            else:
                metric = await self._entity_client.get(entities.Metric, workspace=workspace, name=name)
        except EntityNotFoundError as e:
            raise MetricRetrievalError("METRIC_NOT_FOUND", f"Metric '{workspace}/{name}' not found.") from e
        return self._mapper.entity_to_schema_via_adapter(metric, MetricResponseAdapter)

    async def create(self, metric: entities.Metric, sdk: AsyncNeMoPlatform) -> MetricResponse:
        """
        Verify secret references before creating entity.

        Args:
            metric: The metric entity to create.
            sdk: SDK instance with request-scoped user context. Required and must be obtained
                 from Depends(get_sdk_client) in API endpoints to ensure proper user context.
        """
        secrets: list[SecretRef | ApiSecretRef] = []
        if isinstance(metric, entities.RemoteMetric | entities.NemoAgentToolkitRemoteMetric):
            if metric.api_key_secret is not None:
                secrets.append(metric.api_key_secret)

        if isinstance(metric, entities.LLMJudgeMetric):
            _append_model_secret(secrets, metric.model)
        elif isinstance(metric, _RAGASJudgeConfig):
            _append_model_secret(secrets, metric.judge_model)
            if isinstance(metric, _RAGASEmbeddingsConfig):
                _append_model_secret(secrets, metric.embeddings_model)
        for secret in secrets:
            try:
                _ = await sdk.secrets.retrieve(secret.root, workspace=metric.workspace)
            except NotFoundError as e:
                raise MetricCreationError(
                    "SECRET_NOT_FOUND",
                    f"Secret '{metric.workspace}/{secret.root}' specified in metric {metric.name!r} not found.",
                ) from e

        resp = await self._entity_client.create(metric)
        return self._mapper.entity_to_schema_via_adapter(resp, MetricResponseAdapter)

    async def create_from_request(
        self, name: str, workspace: str, request: Metric, sdk: AsyncNeMoPlatform
    ) -> MetricResponse:
        """Create a metric entity from a request DTO.

        Uses MetricMapper to handle model resolution and entity construction,
        then validates secrets before persisting.

        Args:
            name: Metric name (from path parameter)
            workspace: Workspace (from path parameter)
            request: Metric request DTO
            sdk: SDK instance with request-scoped user context. Required and must be obtained
                 from Depends(get_sdk_client) in API endpoints to ensure proper user context.
            request: The metric request DTO

        Returns:
            The created metric entity
        """
        try:
            metric = await self._mapper.request_to_entity(request, name, workspace)
        except ValueError as e:
            raise MetricCreationError("INVALID_METRIC", str(e)) from e
        return await self.create(metric, sdk)

    async def delete(self, workspace: str, name: str) -> DeleteResponse:
        try:
            metric = await self._entity_client.get(entities.Metric, workspace=workspace, name=name)
        except EntityNotFoundError as e:
            raise MetricDeletionError("METRIC_NOT_FOUND", f"Metric '{workspace}/{name}' not found.") from e
        await self._entity_client.delete(entities.Metric, metric.name, workspace=workspace)
        return DeleteResponse(
            message="Resource deleted successfully",
            id=f"{workspace}/{name}",
            deleted_at=datetime.now(timezone.utc),
        )

    async def exists(self, workspace: str, name: str) -> bool:
        try:
            await self._entity_client.get(entities.Metric, workspace=workspace, name=name)
        except EntityNotFoundError:
            return False
        return True

    async def get_metric(
        self, metric: app.MetricRef | Metric | app.Metric | entities.Metric | entities.SystemMetric
    ) -> app.Metric:
        """
        Get a metric from a reference, inline definition, or entity.

        - References are looked up from the entity store
        - Inline metrics have their ModelRef fields resolved, then are converted to app-layer types
        - Entity-based metrics are validated and returned

        Args:
            metric: Reference (e.g. "workspace/name"), inline definition, or entity.

        Returns:
            The metric configuration with all ModelRef fields resolved to Model.

        Raises:
            MetricRetrievalError: If reference points to a non-existent metric.
            MetricResolutionError: If metric uses reserved 'system' workspace.
        """
        if isinstance(metric, app.MetricRef):
            # String reference - look up stored metric
            workspace, name = metric.root.split("/")
            referenced_metric = await self.get_by_name(workspace, name)
            if referenced_metric is None:
                raise MetricRetrievalError("METRIC_NOT_FOUND", f"Metric '{workspace}/{name}' not found.")
            return app.MetricAdapter.validate_python(referenced_metric.model_dump(exclude_none=True))

        if isinstance(metric, EntityBase):
            return app.MetricAdapter.validate_python(metric.model_dump(exclude_none=True))

        # Resolve any ModelRef fields to Model before converting to app-layer types.
        # API-layer metrics may have ModelRef strings (e.g. "workspace/model_name") for
        # model fields. These must be resolved to concrete Model instances because
        # the app layer only accepts Model.
        data = metric.model_dump(exclude_none=True)
        if isinstance(metric, ResolvableModels):
            resolved_models = await metric.resolve_models(resolve_model)
            data.update({k: v.model_dump() for k, v in resolved_models.items()})

        return app.MetricAdapter.validate_python(data)

    async def compile_job(self, workspace: str, job: MetricJob, sdk: AsyncNeMoPlatform) -> PlatformJobSpec:
        """Compile a metric job input to a platform job spec.

        This method:
        1. Retrieves the metric entity from the reference
        2. Validates prechecks (fileset exists)
        3. Compiles to platform job spec

        Args:
            workspace: The workspace for the job (from API path parameter).
            job: The metric job input specification.
            sdk: SDK instance with request-scoped user context. Required and must be obtained
                 from Depends(get_sdk_client) in API endpoints to ensure proper user context.

        Returns:
            Platform job specification ready for execution.

        Raises:
            MetricRetrievalError: If metric reference points to a non-existent metric.
            MetricResolutionError: If metric uses reserved 'system' workspace.
            ValueError: If prechecks fail or compilation fails.
        """
        refs = {}
        if isinstance(job.metric, app.MetricRef):
            refs["metric_ref"] = job.metric
        if isinstance(job.dataset, app.FilesetRef):
            refs["dataset_ref"] = job.dataset

        # Resolve metric reference (also resolves any ModelRef fields for inline metrics)
        metric = await self.get_metric(job.metric)

        # Resolve model refs in metric_params (for metrics with judge models like RAGAS metrics)
        job.metric_params = await resolve_params_model_refs(job.metric_params)

        # Resolve ModelRef fields on job surfaces before prechecks and app-layer validation.
        if isinstance(job, MetricOnlineJob):
            if isinstance(job.model, app.ModelRef):
                refs["model_ref"] = job.model
            job.model = await resolve_model(job.model)
        if isinstance(job, MetricRetrieverJob):
            job.retriever_pipeline.embeddings_model = await resolve_model(job.retriever_pipeline.embeddings_model)

        # Run prechecks (fileset exists + model reachability)
        result = await CompositeCheck(
            job_fileset_exists_check(job, sdk=sdk),
            job_model_check(job, workspace, sdk=sdk),
            metric_dataset_schema_check(job, metric, sdk),
        )()
        if not result.status:
            raise ValueError(f"Job cannot be launched. Error: {str(result)}")

        # Convert API schema to MetricJob and compile
        job_data = job.model_dump(exclude_none=True)
        job_data["metric"] = metric.model_dump(exclude_none=True)
        job_data.update(refs)
        job_data = rewrite_models_for_job_container(job_data)
        compiled_job = await compile_metric_job(app.MetricJobAdapter.validate_python(job_data))
        return compiled_job

    def _build_secret_resolver(self, workspace: str, sdk: AsyncNeMoPlatform) -> SecretResolver:
        """Build a secret resolver that uses the provided SDK instance.

        Args:
            workspace: Workspace for resolving secrets.
            sdk: SDK instance with request-scoped user context. Required and must be obtained
                 from Depends(get_sdk_client) in API endpoints to ensure proper user context.
        """

        return _PlatformSecretResolver(workspace=workspace, sdk=sdk)

    async def evaluate(
        self,
        workspace: str,
        metric_ref: app.MetricRef | Metric,
        dataset: DatasetRows,
        sdk: AsyncNeMoPlatform,
        limit_samples: int = 100,
        aggregate_fields: frozenset[AggregateFieldName] | None = None,
    ) -> MetricEvaluationResponse:
        """
        Run a metric evaluation on a dataset.

        This method orchestrates the full evaluation:
        1. Resolves the metric (reference lookup or inline validation)
        2. Instantiates the metric for computation
        3. Runs evaluation via the app layer
        4. Returns the API response directly

        Args:
            workspace: Workspace context for the evaluation.
            metric_ref: Either a reference, inline metric definition, or resolved Metric.
            dataset: Inline dataset with rows.
            sdk: SDK instance with request-scoped user context. Required and must be obtained
                 from Depends(get_sdk_client) in API endpoints to ensure proper user context.
            limit_samples: Maximum number of rows to evaluate.
            aggregate_fields: Fields to include in aggregate scores. Defaults to
                DefaultAggregateFieldName values if not specified.

        Returns:
            MetricEvaluationResponse ready for API serialization.

        Raises:
            MetricRetrievalError: If reference points to a non-existent metric.
            MetricEvaluationError: If metric initialization or evaluation fails.
        """
        rows = dataset.rows[:limit_samples]

        # Resolve stored metric params (not runtime metric model) reference
        metric_config = await self.get_metric(metric_ref)

        # Generate identifier for logging
        metric_id = (
            f"{metric_config.workspace}/{metric_config.name}"
            if isinstance(metric_config, EntityBase)
            else f"{metric_config.type}/_inline"
        )

        _logger.info("Running metric evaluation", extra={"metric": metric_id, "row_count": len(rows)})

        # Build secret resolver for this metric
        secret_resolver = self._build_secret_resolver(workspace, sdk)

        # Instantiate the metric
        try:
            metric_impl = await new_metric(
                metric_config,
                job_type=SupportedJobTypes.OFFLINE,
                secret_resolver=secret_resolver,
                run_preflight=True,
            )
        except ValueError as e:
            raise MetricEvaluationError(
                "EVALUATION_FAILED",
                f"Failed to initialize metric '{metric_id}': {e}",
            ) from e

        # Build pipeline (offline: model=None, no inference)
        pipeline = ComputeMetricPipeline(
            rows=rows,
            parallelism=DEFAULT_PARALLELISM,
            metric=metric_impl,
            target=None,
            metric_key=metric_type_name(metric_impl),
        )

        try:
            results = await run_generated_sample_scoring_pipeline(pipeline)
        except Exception as e:
            eval_error = get_evaluation_error(e)
            if isinstance(eval_error, EvaluationError):
                detail = f"Evaluation failed at row {eval_error.index}: {eval_error.message}"
            else:
                _logger.exception(
                    "Unexpected failure during metric evaluation",
                    extra={"metric": metric_id, "error_type": type(e).__name__, "error_message": str(e)},
                )
                detail = str(eval_error)
            raise MetricEvaluationError("EVALUATION_FAILED", detail) from e

        try:
            evaluation_result = await finalize_evaluation_result(metric_impl, results, skip_errored=True)

            # Determine which fields to include in aggregate scores
            fields: frozenset[AggregateFieldName] = (
                aggregate_fields if aggregate_fields is not None else _default_aggregate_fields()
            )
            agg_scores = [score.with_fields(fields) for score in evaluation_result.aggregate_scores.scores]

            # Convert SDK row scores to API response format
            row_scores = []
            failed_count = 0
            for fallback_index, row_score in enumerate(evaluation_result.row_scores):
                if row_score.metric_errors:
                    failed_count += 1
                row_index = row_score.row_index if row_score.row_index is not None else fallback_index
                if row_index < 0 or row_index >= len(rows):
                    raise MetricEvaluationError(
                        "EVALUATION_FAILED",
                        f"Pipeline returned out-of-bounds row_index={row_index} for {len(rows)} rows",
                    )
                row_scores.append(
                    MetricEvaluationRowScore.from_row_score(
                        row_score,
                        row=rows[row_index],
                        index=row_index,
                    )
                )

            _logger.info(
                "Metric evaluation completed",
                extra={
                    "success_count": len(row_scores) - failed_count,
                    "failed_count": failed_count,
                },
            )

            return MetricEvaluationResponse(
                metric=MetricResponseAdapter.validate_python(metric_config.model_dump(exclude_none=True)),
                aggregate_scores=agg_scores,
                row_scores=row_scores,
            )
        except MetricEvaluationError:
            raise
        except Exception as e:
            _logger.exception(
                "Unexpected failure during post-pipeline metric evaluation",
                extra={"metric": metric_id, "error_type": type(e).__name__, "error_message": str(e)},
            )
            raise MetricEvaluationError("EVALUATION_FAILED", str(e)) from e

    # =============================================================================
    # Metric Job Results
    # =============================================================================

    async def delete_job_result(self, workspace: str, name: str) -> DeleteResponse:
        try:
            await self._entity_client.get(entities.MetricJobResult, workspace=workspace, name=name)
        except EntityNotFoundError as e:
            raise MetricDeletionError(
                "METRIC_JOB_RESULT_NOT_FOUND", f"Metric job result '{workspace}/{name}' not found."
            ) from e
        await self._entity_client.delete(entities.MetricJobResult, name, workspace=workspace)
        return DeleteResponse(
            message="Resource deleted successfully",
            id=f"{workspace}/{name}",
            deleted_at=datetime.now(timezone.utc),
        )

    async def get_job_result(
        self, workspace: str, name: str, aggregate_fields: frozenset[AggregateFieldName] | None = None
    ) -> MetricJobResult:
        """Get a metric job result."""
        try:
            result: entities.MetricJobResult = await self._entity_client.get(
                entities.MetricJobResult, workspace=workspace, name=name
            )
        except EntityNotFoundError as e:
            raise MetricRetrievalError(
                "METRIC_JOB_RESULT_NOT_FOUND", f"Metric job result '{workspace}/{name}' not found."
            ) from e

        job_result = self._mapper.entity_to_schema(result, MetricJobResult)
        if aggregate_fields:
            job_result.scores = [score.with_fields(aggregate_fields) for score in job_result.scores]
        return job_result

    async def get_job_results(
        self,
        workspace: str,
        aggregate_fields: frozenset[AggregateFieldName] | None = None,
        page: int = 1,
        page_size: int = 100,
        sort: Literal["-created_at", "created_at", "-updated_at", "updated_at", "-name", "name"] = "-created_at",
        parsed_filter: ParsedFilter | None = None,
    ) -> MetricJobResultsListResponse:
        """List metric job results with optional filtering, pagination, and sorting."""
        filter_op = parsed_filter.operation if parsed_filter else None
        resp = await self._entity_client.list(
            entities.MetricJobResult,
            workspace=workspace,
            sort=sort,
            page=page,
            page_size=page_size,
            filter_operation=filter_op,
        )

        metrics = [self._mapper.entity_to_schema(result, MetricJobResult) for result in resp.data]

        if aggregate_fields:
            for result in metrics:
                result.scores = [score.with_fields(aggregate_fields) for score in result.scores]

        return MetricJobResultsListResponse(
            data=metrics,
            pagination=PaginationData(**resp.pagination.model_dump()),
            sort=sort,
            filter=parsed_filter.to_response() if parsed_filter else None,
        )

    # =============================================================================
    # System Metrics
    # =============================================================================

    @retry(
        stop=stop_after_attempt(10),
        wait=wait_exponential(multiplier=1, min=4, max=15),
    )
    async def _get_registered_system_metrics(self) -> ListResponse[entities.SystemMetric]:
        # Intentionally bypass get_all(): it returns API DTOs with optional entity metadata,
        # while this internal startup/cleanup path needs concrete SystemMetric entities.
        return await self._entity_client.list(
            entities.SystemMetric,
            workspace=SYSTEM_WORKSPACE,
            page_size=1000,
        )

    @retry(
        stop=stop_after_attempt(10),
        wait=wait_exponential(multiplier=1, min=4, max=30),
    )
    async def _ensure_system_workspace_exists(self) -> None:
        # Use service principal if configured for startup/background tasks
        _ = await get_async_platform_sdk(as_service=self._as_service, internal=True).workspaces.retrieve(
            SYSTEM_WORKSPACE
        )

    async def delete_all_system_metrics(self) -> None:
        registered_system_metrics_list = await self._get_registered_system_metrics()
        tasks = []
        for metric in registered_system_metrics_list.data:
            if metric.name is None:
                _logger.warning("Skipping system metric deletion because the registered metric has no name")
                continue
            _logger.debug("Deleting system metric from entity service", extra={"metric": metric.name})
            tasks.append(self._entity_client.delete(entities.SystemMetric, metric.name, workspace=SYSTEM_WORKSPACE))
        await asyncio.gather(*tasks)
        _logger.info("Deleted system metrics from the entity service", extra={"count": len(tasks)})

    async def register_system_metrics(self, recreate_existing: bool = False) -> None:
        # TODO: This is a temporary solution to ensure that the system metrics are registered in the entity service.
        # We need to align on the right approach for seed data.
        with scoped_otel_headers(MARK_INTERNAL_REQUEST_HEADERS):
            await self._register_system_metrics_impl(recreate_existing)

    async def _register_system_metrics_impl(self, recreate_existing: bool) -> None:
        await self._ensure_system_workspace_exists()
        if recreate_existing:
            _logger.info("Reregistering system metrics in the entity service...")
            await self.delete_all_system_metrics()
        else:
            _logger.info("Registering system metrics in the entity service...")
        registered_system_metrics_list = await self._get_registered_system_metrics()
        registered_system_metrics = {metric.name: metric for metric in registered_system_metrics_list.data}

        tasks = []
        system_metrics = get_all_system_metrics()
        metrics_warning = []

        # Use service SDK for system metric registration (startup task)
        service_sdk = get_async_platform_sdk(as_service=self._as_service, internal=True)
        for metric in system_metrics:
            metric_entity = entities.SystemMetric(**metric.model_dump(exclude_none=True))
            if metric.name not in registered_system_metrics:
                _logger.debug("Creating system metric in entity service", extra={"metric": metric.name})
                tasks.append(self.create(metric_entity, sdk=service_sdk))
            elif not _metrics_equal(registered_system_metrics[metric.name], metric_entity):
                metrics_warning.append(metric.name)
            else:
                _logger.debug("System metric is up to date in entity service", extra={"metric": metric.name})
        if metrics_warning:
            _logger.warning("System metric is not up to date in entity service", extra={"metrics": metrics_warning})

        await asyncio.gather(*tasks)
        _logger.info("Registered new system metrics in the entity service", extra={"count": len(tasks)})
