# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""NemoJobScheduler — the runtime that drives ``run`` / ``submit`` / ``explain``.

Three entry points, one per CLI verb generated by
:func:`~nemo_platform_plugin.commands.add_job_commands`:

- :meth:`NemoJobScheduler.run_local` — execute the job in-process. Validates
  the spec against :attr:`~nemo_platform_plugin.job.NemoJob.input_spec_schema` (or
  :attr:`~nemo_platform_plugin.job.NemoJob.spec_schema`), invokes
  :meth:`~nemo_platform_plugin.job.NemoJob.to_spec` when an input shape is declared,
  then calls ``job.run(...)``.
- :meth:`NemoJobScheduler.submit_remote` — POST the job to the plugin
  service's per-job endpoint.
- :meth:`NemoJobScheduler.explain` — read-only schema introspection.

Spec handling for ``run(config)``:

When :attr:`~nemo_platform_plugin.job.NemoJob.spec_schema` is declared, the scheduler
validates the incoming dict against it and passes ``spec.model_dump()`` to
``run``. When ``spec_schema`` is ``None``, the raw dict is forwarded
unchanged. Jobs that declare extra keyword-only parameters on ``run``
(``ctx``, ``sdk``, ``async_sdk``) receive them via signature-based DI —
see :func:`~nemo_platform_plugin.run_dependencies.resolve_run_kwargs`.
"""

from __future__ import annotations

import asyncio
import logging
import os
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx
from nemo_platform_plugin.job import job_collection_path_for
from nemo_platform_plugin.job_context import JobContext, StoragePaths
from nemo_platform_plugin.job_results import LocalJobResults
from nemo_platform_plugin.run_dependencies import resolve_run_kwargs

# Environment variables the in-container runtime sets and that legacy task
# code reads via ``os.environ.get(...)``. The scheduler mirrors them onto the
# process for the duration of ``run_local`` so existing task code keeps
# working without modification when invoked from the local CLI.
_PERSISTENT_STORAGE_ENVVAR = "NEMO_JOB_PERSISTENT_JOB_STORAGE_PATH"
_EPHEMERAL_STORAGE_ENVVAR = "NEMO_JOB_EPHEMERAL_TASK_STORAGE_PATH"
_JOB_ID_ENVVAR = "NEMO_JOB_ID"
_WORKSPACE_ENVVAR = "NEMO_JOB_WORKSPACE"

if TYPE_CHECKING:
    from nemo_platform_plugin.job import NemoJob


logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Scheduler
# ---------------------------------------------------------------------------


class NemoJobScheduler:
    """Drives the three execution verbs (``run`` / ``submit`` / ``explain``).

    Construction-cheap — instantiate per CLI invocation. All state is
    derived from the :class:`NemoJob` subclass and the submitter-provided
    spec. The ``sdk`` and ``async_sdk`` kwargs on :meth:`run_local` are
    opt-in hooks for jobs that need SDK access; the scheduler does not
    construct them on its own.
    """

    # ------------------------------------------------------------------ #
    # Local execution                                                    #
    # ------------------------------------------------------------------ #

    def run_local(
        self,
        job_cls: type["NemoJob"],
        spec: dict,
        *,
        workspace: str = "default",
        sdk: object | None = None,
        async_sdk: object | None = None,
        ctx: JobContext | None = None,
    ) -> dict:
        """Execute *job_cls* locally, in-process.

        Sync entry point. The async portion of the job lifecycle —
        ``to_spec`` — runs once via :func:`asyncio.run` to produce the
        canonical spec; the sync ``run`` is invoked directly. Method
        colours follow the execution-context rule: ``to_spec`` /
        ``compile`` are async (API-side); ``run`` is sync (task
        container).

        Args:
            job_cls: :class:`~nemo_platform_plugin.job.NemoJob` subclass.
            spec: Submitter input as a plain ``dict``. Validated against
                ``input_spec_schema`` or ``spec_schema`` when declared;
                otherwise passed through unchanged.
            workspace: Workspace scope for the local context.
            sdk: Optional :class:`~nemo_platform.NeMoPlatform` handle.
                Bound to an ``sdk`` kwarg on ``run`` if the signature
                declares one. Jobs obtain typed service clients via
                ``client_from_platform(sdk, FilesClient)`` for
                per-service operations.
            async_sdk: Optional :class:`~nemo_platform.AsyncNeMoPlatform`
                handle, bound the same way when an ``async_sdk`` kwarg
                is declared. Sync ``run`` cannot consume this directly
                — it's available for jobs that delegate to async
                helpers via :func:`asyncio.run`.
            ctx: Optional :class:`JobContext`. When omitted, the
                scheduler builds one with tempdir-backed storage and a
                :class:`LocalJobResults` sink.

        Returns:
            The job's ``dict`` result from :meth:`NemoJob.run`.
        """
        _ensure_local_logging_configured()
        canonical = asyncio.run(
            self._prepare_canonical_spec(
                job_cls,
                spec,
                workspace=workspace,
                async_sdk=async_sdk,
                is_local=True,
            )
        )
        ctx = ctx or self._build_local_context(job_cls, workspace=workspace)
        # Note: scheduler-built tempdirs are intentionally not torn down here.
        # ``ctx.results`` URLs (``file://...``) must outlive ``run_local`` so
        # callers can read the artifacts they pointed at. The OS reaps the
        # ``nemo-platform-plugin-*`` dirs under ``$TMPDIR``; tests that need hermetic
        # directories should pass an explicit ``ctx`` with ``tmp_path``.
        return self._invoke_run(job_cls, canonical, sdk=sdk, async_sdk=async_sdk, ctx=ctx)

    # ------------------------------------------------------------------ #
    # Remote submission                                                  #
    # ------------------------------------------------------------------ #

    def submit_remote(
        self,
        job_cls: type["NemoJob"],
        spec: dict,
        *,
        base_url: str | None = None,
        workspace: str = "default",
        profile: str | None = None,
        options: dict | None = None,
        metadata: dict | None = None,
        http_client: httpx.Client | None = None,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
    ) -> dict:
        """POST the job to the plugin service's per-job submit route.

        Builds the submit URL from
        :attr:`~nemo_platform_plugin.job.NemoJob.job_collection_path` and POSTs a JSON body of
        ``{**metadata, "spec": ..., "profile": ..., "options": ...}``.

        Args:
            job_cls: The :class:`~nemo_platform_plugin.job.NemoJob` subclass.
            spec: Submitter input (validated server-side against
                ``input_spec_schema`` / ``spec_schema``).
            base_url: Final plugin-service base URL
                (e.g. ``"https://nmp.dev.example"``).
            workspace: Workspace scope for the submit URL.
            profile: Profile label forwarded to the server.
            options: Opaque wire ``{"<backend>": {...}}`` bag.
            metadata: Optional envelope fields (``name``, ``description``,
                ``project``, ``ownership``, ``custom_fields``).
            http_client: Optional injected :class:`httpx.Client`. Defaults
                to a short-lived client per call; tests supply a mock
                transport.
            headers: Optional per-request headers (e.g. ``Authorization`` from
                the CLI). Merged on each POST; not inferred from *http_client*.
            timeout: Request timeout in seconds.

        Returns:
            The decoded JSON response from the plugin service.

        Raises:
            ValueError: If no ``base_url`` is provided.
            httpx.HTTPStatusError: On 4xx / 5xx responses.
        """
        url = self._build_submit_url(job_cls, base_url=base_url, workspace=workspace)
        body = self._build_submit_body(spec, profile=profile, options=options, metadata=metadata)
        return self._post_submit(url, body, http_client=http_client, headers=headers, timeout=timeout)

    # ------------------------------------------------------------------ #
    # Schema discovery                                                   #
    # ------------------------------------------------------------------ #

    def explain(
        self,
        job_cls: type["NemoJob"],
        *,
        profile: str | None = None,
    ) -> dict:
        """Return a schema bundle for *job_cls* — no network.

        The CLI holds a live reference to ``job_cls``, so
        ``spec_schema`` / ``input_spec_schema`` JSON Schemas are read
        directly via :meth:`model_json_schema` without touching the
        plugin service.

        Args:
            job_cls: The :class:`~nemo_platform_plugin.job.NemoJob` subclass.
            profile: Profile label to annotate the bundle with.

        Returns:
            Dict with keys ``job_key``, ``endpoint``, ``spec_schema``,
            ``input_spec_schema``, ``profile``, ``profile_providers``,
            ``options``. ``endpoint`` is a URL path template with
            ``{workspace}`` left as a literal placeholder.
            ``profile_providers`` / ``options`` are currently empty —
            they're populated once the Jobs service endpoints for
            operator-configured profiles and backend options are wired.
        """
        spec_schema = job_cls.spec_schema.model_json_schema() if job_cls.spec_schema else None
        input_spec_schema = job_cls.input_spec_schema.model_json_schema() if job_cls.input_spec_schema else None

        return {
            "job_key": _job_key_for(job_cls),
            "endpoint": submit_path_for(job_cls, workspace="{workspace}"),
            "spec_schema": spec_schema,
            "input_spec_schema": input_spec_schema,
            "profile": profile,
            "profile_providers": [],
            "options": {},
        }

    # ------------------------------------------------------------------ #
    # Internal helpers                                                   #
    # ------------------------------------------------------------------ #

    async def _prepare_canonical_spec(
        self,
        job_cls: type["NemoJob"],
        spec: dict,
        *,
        workspace: str,
        async_sdk: object | None,
        is_local: bool,
    ) -> dict:
        """Return the spec as a ``dict`` ready for :meth:`run`.

        - If ``input_spec_schema`` is declared: validate against it and
          pass the result through the ``async classmethod`` ``to_spec``
          to produce the canonical instance; return
          ``canonical.model_dump()``.
        - Else if ``spec_schema`` is declared: validate against it and
          return ``validated.model_dump()`` (normalises defaults,
          coerces types).
        - Else: return *spec* unchanged.

        ``async`` because :meth:`NemoJob.to_spec` is an
        ``async classmethod`` (runs in API context). The caller drives
        this through :func:`asyncio.run` from :meth:`run_local`.

        ``async_sdk`` is the SDK handle forwarded to ``to_spec``.
        ``to_spec`` only accepts an async client by convention (the
        method is itself ``async`` and runs in the API process); the
        local path matches the production API contract so plugin
        authors don't need a sync/async branch.

        ``is_local`` is always forwarded because it is part of the
        ``to_spec`` lifecycle signature.
        """
        input_schema = job_cls.input_spec_schema or job_cls.spec_schema
        if input_schema is None:
            return spec

        validated = input_schema.model_validate(spec, context={"is_local": is_local})

        if job_cls.input_spec_schema is not None:
            canonical = await job_cls.to_spec(
                validated,
                workspace=workspace,
                entity_client=None,
                async_sdk=async_sdk,
                is_local=is_local,
            )
            # Re-validate ``to_spec`` output against ``spec_schema`` so plugin
            # authors can't widen the canonical shape by accident — ``run``
            # always sees the schema the rest of the stack advertises.
            if job_cls.spec_schema is not None:
                canonical = job_cls.spec_schema.model_validate(canonical, context={"is_local": is_local})
            return canonical.model_dump()

        return validated.model_dump()

    def _invoke_run(
        self,
        job_cls: type["NemoJob"],
        canonical: dict,
        *,
        sdk: object | None,
        async_sdk: object | None,
        ctx: JobContext,
    ) -> dict:
        """Call ``job.run(...)`` with signature-based dependency injection.

        Keyword-only parameters on ``run`` are resolved by name:

        - ``ctx: JobContext`` — bound to the constructed context.
        - ``sdk`` — bound to the *sdk* argument.
        - ``async_sdk`` — bound to the *async_sdk* argument.
        - ``is_local`` — bound to ``True`` because this is the local runner.

        Required parameters (no default) raise :class:`LocalRunError` before
        ``run`` is called when the scheduler can't resolve them. Parameters
        with a default (typically ``Optional[X] = None``) are left unbound
        and fall back to the declared default.

        ``run(self, config)`` (no extra parameters) is also supported and
        receives only the canonical dict.
        """
        logger.debug(
            "Running job %r locally (workspace=%s, job_id=%s)",
            job_cls.name,
            ctx.workspace,
            ctx.job_id,
        )
        job = job_cls()
        kwargs = resolve_run_kwargs(job_cls, job.run, sdk=sdk, async_sdk=async_sdk, ctx=ctx, is_local=True)
        with _local_runtime_env(ctx):
            return job.run(canonical, **kwargs)

    # ---- submit_remote helpers ------------------------------------- #

    def _build_submit_url(
        self,
        job_cls: type["NemoJob"],
        *,
        base_url: str | None,
        workspace: str,
    ) -> str:
        """Construct the full submit URL for *job_cls*.

        Uses ``job_cls.job_collection_path`` or the default
        ``/jobs/{job_cls.name}`` collection path.
        Base URL must already be resolved by the CLI layer.
        """
        endpoint = submit_path_for(job_cls, workspace=workspace)
        if not base_url:
            raise ValueError(
                "submit_remote requires base_url; the CLI should resolve cluster and env fallbacks before calling it."
            )
        return f"{base_url.rstrip('/')}{endpoint}"

    def _build_submit_body(
        self,
        spec: dict,
        *,
        profile: str | None,
        options: dict | None,
        metadata: dict | None,
    ) -> dict[str, Any]:
        """Assemble the POST body ``{**metadata, "spec", "profile", "options"}``."""
        body: dict[str, Any] = {}
        if metadata:
            body.update(metadata)
        body["spec"] = spec
        if profile is not None:
            body["profile"] = profile
        if options:
            body["options"] = options
        return body

    def _post_submit(
        self,
        url: str,
        body: dict[str, Any],
        *,
        http_client: httpx.Client | None,
        headers: dict[str, str] | None,
        timeout: float,
    ) -> dict:
        """POST *body* to *url* and return the decoded JSON response.

        Uses *http_client* when provided; otherwise opens a short-lived
        client per call.
        """
        request_headers = dict(headers) if headers else None
        logger.debug("submit_remote POST %s", url)
        if http_client is not None:
            response = http_client.post(url, json=body, headers=request_headers, timeout=timeout)
        else:
            with httpx.Client(timeout=timeout) as client:
                response = client.post(url, json=body, headers=request_headers)
        response.raise_for_status()
        return response.json()

    # ---- local-context builder ------------------------------------- #

    def _build_local_context(self, job_cls: type["NemoJob"], *, workspace: str) -> JobContext:
        """Build a :class:`JobContext` for local execution.

        Creates a tempdir with ``ephemeral/`` and ``persistent/``
        subdirectories that outlive the scheduler call, and wires a
        :class:`LocalJobResults` sink rooted at ``persistent/results/``.

        ``job_id`` is left ``None`` for scheduler-created local contexts.
        """
        root = Path(tempfile.mkdtemp(prefix="nemo-platform-plugin-", suffix=f"-{job_cls.name}"))
        ephemeral = root / "ephemeral"
        persistent = root / "persistent"
        ephemeral.mkdir(parents=True, exist_ok=True)
        persistent.mkdir(parents=True, exist_ok=True)
        results_root = persistent / "results"
        storage = StoragePaths(ephemeral=ephemeral, persistent=persistent)
        return JobContext(
            workspace=workspace,
            storage=storage,
            results=LocalJobResults(root=results_root),
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@contextmanager
def _local_runtime_env(ctx: JobContext):
    """Mirror the in-container runtime envvars onto the process during ``run``.

    Legacy task code (and the existing per-service compilers) reads
    ``NEMO_JOB_PERSISTENT_JOB_STORAGE_PATH`` and friends via ``os.environ``
    to locate scratch / persistent volumes. Inside a real job pod the Jobs
    controller injects them; in local mode the scheduler synthesizes a
    :class:`JobContext` with tempdir-backed storage and exposes the
    same envvars here so unmodified task code keeps working.

    Caller-set storage values win — we only fill storage envvars that aren't
    already set. The workspace envvar always reflects the current local
    context so a parent job's workspace does not leak into nested local runs.
    Prior environment values are restored on exit so tests and back-to-back
    calls don't leak state.
    """
    storage_overrides: dict[str, str] = {
        _PERSISTENT_STORAGE_ENVVAR: str(ctx.storage.persistent),
        _EPHEMERAL_STORAGE_ENVVAR: str(ctx.storage.ephemeral),
    }
    # Scheduler-built local contexts leave job_id as ``None``. Explicit
    # caller-provided contexts may still mirror a job id for legacy code.
    force_overrides: dict[str, str] = {_WORKSPACE_ENVVAR: ctx.workspace}
    if ctx.job_id is not None:
        force_overrides[_JOB_ID_ENVVAR] = ctx.job_id
    saved: dict[str, str | None] = {}
    try:
        for key, value in storage_overrides.items():
            if key in os.environ:
                continue  # respect explicit caller setup
            saved[key] = None
            os.environ[key] = value
        for key, value in force_overrides.items():
            saved[key] = os.environ.get(key)
            os.environ[key] = value
        yield
    finally:
        for key, prior in saved.items():
            if prior is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = prior


def _job_key_for(job_cls: type["NemoJob"]) -> str:
    """Best-effort entry-point key for *job_cls*.

    Uses the API segment (top-level package, ``nemo_`` prefix stripped, hyphenated)
    as a fallback when no registered entry point is available — e.g. a job in
    ``nemo_data_designer.jobs.generate`` keys as ``data-designer.<job.name>``,
    matching the documented ``<plugin>.<job>`` convention. Scheduler callers
    that have the registered key should pass it explicitly to
    :meth:`NemoJobScheduler.run_local` via a custom ``ctx``.
    """
    return f"{_api_segment_for(job_cls)}.{job_cls.name}"


def submit_path_for(job_cls: type["NemoJob"], *, workspace: str) -> str:
    """The submit URL path (no host / scheme) for *job_cls*.

    Useful for OpenAPI path lookups and explain bundles; mirrors
    :meth:`NemoJobScheduler._build_submit_url` without the host.
    """
    return f"/apis/{_api_segment_for(job_cls)}/v2/workspaces/{workspace}{job_collection_path_for(job_cls)}"


def _api_segment_for(job_cls: type["NemoJob"]) -> str:
    """Derive the ``{api}`` segment of the submit URL for *job_cls*.

    Jobs register under the ``nemo.jobs`` entry-point group keyed as
    ``<plugin>.<job>``, and the platform mounts their routes under that
    ``<plugin>`` segment. The authoritative source of truth is therefore
    the entry-point key — not the Python module path. We resolve it via
    :func:`~nemo_platform_plugin.discovery.discover_jobs` so a plugin registered
    as ``agents.evaluate`` correctly maps to ``/apis/agents/...``, even
    though its package directory is ``nemo_agents_plugin/`` (which the
    module-name heuristic would have collapsed to ``agents-plugin`` and
    404'd against).

    When the job class isn't installed as an entry point — unit tests
    with inline classes, ad-hoc invocations from a checkout — fall back
    to deriving the segment from the top-level package name with the
    ``nemo_`` prefix stripped and underscores converted to dashes.
    The fallback does *not* strip a trailing ``_plugin``: a plugin whose
    actual key happens to be ``my-plugin`` would be silently rewritten
    to ``my``.
    """
    from nemo_platform_plugin.discovery import discover_jobs

    try:
        registered = discover_jobs()
    except Exception:
        registered = {}
    for key, registered_cls in registered.items():
        if registered_cls is job_cls and "." in key:
            return key.split(".", 1)[0]

    module = job_cls.__module__.split(".")[0]
    if module.startswith("nemo_"):
        module = module[len("nemo_") :]
    return module.replace("_", "-")


def _ensure_local_logging_configured() -> None:
    """Attach a stderr INFO handler to the root logger if none is set.

    No-op when the caller already configured logging (CLI with ``-v``,
    service ``dictConfig``, test harness). Noisy transport libraries
    (``httpx``, ``httpcore``) are clamped to WARNING so per-request
    debug output doesn't drown the job's own messages.
    """
    root = logging.getLogger()
    if root.handlers:
        return
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter("%(levelname)s %(message)s"))
    root.addHandler(handler)
    root.setLevel(logging.INFO)
    logging.getLogger("httpx").setLevel(logging.WARNING)
    logging.getLogger("httpcore").setLevel(logging.WARNING)
